remote_theme: bagustris/primer2-theme
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Ramadan
url: "https://bagustris.github.io"
baseurl: "/ramadan"
repository: bagustris/ramadan

exclude:
  - README.md
